### PR TITLE
Add atmospheric fluctuation simulations using toast3

### PR DESCRIPTION
**Pull request by dennis-l**
Adds atmospheric fluctuations from the toast software framework

- `tolteca/simu/toltec/atm.py`: `ToastAtmosphereSimulation` handles the functionality of drawing from the LMT weather site data and generating the atmosphere slabs 
- additions in `tolteca/simu/__init__.py` : calls `ToastAtmosphereSimulation` to generate the slabs based on the parameters of the observation 
- additions `tolteca/simu/toltec/__init__.py`: adds the integration/observation of the atmospheric slabs based on each detector

### CODE REVIEW

**Comment by Jerry-Ma** [comment]
@dennis-l Thanks a lot! To get started, what is the process of installing the toast that works? I see the latest release on hpc4cmb toast is still toast2, but the master branch maybe already toast3. So should I install the master branch?

**Comment by dennis-l** [comment]
@Jerry-Ma The `toast3` branch is the one that should be installed. At this point, I don't think any of the toast3 changes have been merged into the master branch.

**Comment by dennis-l** [comment]
@Jerry-Ma The changes should be all set now. The loading/fluctuations are similar to what the data from AzTEC suggests. I wrapped up some basic tests and everything should be compatible with the most recent commit (https://github.com/hpc4cmb/toast/commit/378952edf13f2ba9a8969503372eab7254f575fa) of the `toast3` branch.

**Comment by Jerry-Ma** [comment]
Thanks a lot, I'll merge and make a test run on the unity cluster.

**Comment by tskisner** [comment]
Thanks for this work @dennis-l and @Jerry-Ma .  Let me know if you have any trouble with the installation of toast3 and dependencies such as `libaatm` (https://github.com/hpc4cmb/libaatm).  When building from source there can be some subtleties with the system BLAS / LAPACK and the equivalent package used by numpy.

We are trying to get a toast-3.0 release candidate on PyPI and conda-forge soon, which should help.

**Comment by Jerry-Ma** [comment]
@tskisner Thanks for the heads-up. I did encountered some issue in building the extensions when using `pip install -e .`, but I was able to successfully build when I switched to using `python setup.py build_ext `. I have not seen anything related to libaatm yet, but I'll keep an eye on it. I'll report back soon after my trial run on our cluster.

**Comment by tskisner** [comment]
Ok, the atmosphere simulation is disabled at runtime unless toast is compiled with `libaatm` and `suitesparse`.  These are bundled with the binary wheels on PyPI, and are packaged in the conda-forge ecosystem.  When compiling toast from source, the build requirements are:
- MKL or FFTW + LAPACK
- libaatm (optional, but used by atmosphere sims)
- suitesparse (option, but used by atmosphere sims)

**Comment by Jerry-Ma** [comment]
Ah, that makes sense. I'll build libaatm and suitesparse. We have ubuntu 20.04 and gcc10 on our cluster. I do see from the build log that it does not pick up suitesparse because I have not specified that. I'll rebuild with the optional dependencies made available and see how it goes.

**Pull request merged**
